// Generated by Supabase CLI - DO NOT EDIT MANUALLY
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      approvals: {
        Row: {
          acted_at: string | null
          approver_id: string
          comment: string | null
          created_at: string
          id: string
          status: string
          step_order: number
          workflow_id: string
        }
        Insert: {
          acted_at?: string | null
          approver_id: string
          comment?: string | null
          created_at?: string
          id?: string
          status?: string
          step_order: number
          workflow_id: string
        }
        Update: {
          acted_at?: string | null
          approver_id?: string
          comment?: string | null
          created_at?: string
          id?: string
          status?: string
          step_order?: number
          workflow_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "approvals_approver_id_fkey"
            columns: ["approver_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "approvals_workflow_id_fkey"
            columns: ["workflow_id"]
            isOneToOne: false
            referencedRelation: "workflows"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_id: string
          created_at: string
          document_id: string | null
          id: string
          metadata: Json | null
        }
        Insert: {
          action: string
          actor_id: string
          created_at?: string
          document_id?: string | null
          id?: string
          metadata?: Json | null
        }
        Update: {
          action?: string
          actor_id?: string
          created_at?: string
          document_id?: string | null
          id?: string
          metadata?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "audit_logs_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
      documents: {
        Row: {
          created_at: string
          creator_id: string
          department: string | null
          file_url: string | null
          id: string
          scope: string
          status: string
          title: string
          type: string
        }
        Insert: {
          created_at?: string
          creator_id: string
          department?: string | null
          file_url?: string | null
          id?: string
          scope: string
          status?: string
          title: string
          type: string
        }
        Update: {
          created_at?: string
          creator_id?: string
          department?: string | null
          file_url?: string | null
          id?: string
          scope?: string
          status?: string
          title?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "documents_creator_id_fkey"
            columns: ["creator_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          created_at: string
          document_id: string | null
          id: string
          message: string
          read: boolean
          user_id: string
        }
        Insert: {
          created_at?: string
          document_id?: string | null
          id?: string
          message: string
          read?: boolean
          user_id: string
        }
        Update: {
          created_at?: string
          document_id?: string | null
          id?: string
          message?: string
          read?: boolean
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "notifications_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "users"
            referencedColumns: ["id"]
          },
        ]
      }
      users: {
        Row: {
          created_at: string
          department: string | null
          email: string
          full_name: string
          id: string
          role: string
        }
        Insert: {
          created_at?: string
          department?: string | null
          email: string
          full_name: string
          id?: string
          role: string
        }
        Update: {
          created_at?: string
          department?: string | null
          email?: string
          full_name?: string
          id?: string
          role?: string
        }
        Relationships: []
      }
      workflows: {
        Row: {
          created_at: string
          document_id: string
          generated_steps: Json
          id: string
          policy_valid: boolean
        }
        Insert: {
          created_at?: string
          document_id: string
          generated_steps?: Json
          id?: string
          policy_valid?: boolean
        }
        Update: {
          created_at?: string
          document_id?: string
          generated_steps?: Json
          id?: string
          policy_valid?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "workflows_document_id_fkey"
            columns: ["document_id"]
            isOneToOne: false
            referencedRelation: "documents"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">
type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never


// Enum types for type safety
export type UserRole = 'faculty' | 'hod' | 'coe' | 'principal' | 'admin'
export type DocumentType = 'notice' | 'timetable' | 'exam_schedule' | 'policy'
export type DocumentScope = 'department' | 'college' | 'institution'
export type DocumentStatus = 'draft' | 'pending' | 'approved' | 'rejected'
export type ApprovalStatus = 'pending' | 'approved' | 'rejected'

// WorkflowStep type definition
export interface WorkflowStep {
  stepOrder: number
  requiredRole: string
  status: 'pending' | 'approved' | 'rejected'
}

// Document type
export interface Document {
  id: string
  title: string
  type: 'notice' | 'timetable' | 'exam_schedule' | 'policy'
  creator_id: string
  department: string
  scope: 'department' | 'college' | 'institution'
  file_url: string | null
  status: 'draft' | 'pending' | 'approved' | 'rejected'
  created_at: string
  category: string | null
  publication_date: string | null
  published_at: string | null
  is_published: boolean
  notice_content: string | null
}

// NoticeRecipient type
export interface NoticeRecipient {
  id: string
  document_id: string
  recipient_type: 'role' | 'department'
  recipient_value: string
  created_at: string
}

// PublishedNotice type
export interface PublishedNotice {
  id: string
  title: string
  type: string
  category: string | null
  department: string
  scope: string
  file_url: string | null
  notice_content: string | null
  publication_date: string | null
  published_at: string | null
  creator_id: string
  created_at: string
  creator_name: string
  creator_role: string
}

// Approval type
export interface Approval {
  id: string
  workflow_id: string
  approver_id: string | null
  step_order: number
  status: 'pending' | 'approved' | 'rejected'
  signature_url: string | null
  signed_at: string | null
  comment: string | null
  acted_at: string | null
}

// Workflow type
export interface Workflow {
  id: string
  document_id: string
  generated_steps: WorkflowStep[]
  policy_valid: boolean
  created_at: string
}

// AuditLog type
export interface AuditLog {
  id: string
  document_id: string
  actor_id: string
  action: string
  metadata: Record<string, unknown>
  created_at: string
}

// Notification type
export interface Notification {
  id: string
  user_id: string
  message: string
  document_id: string
  read: boolean
  created_at: string
}

// User type (from database)
export type User = Tables<'users'>

// Insert types
export type UserInsert = TablesInsert<'users'>
export type DocumentInsert = TablesInsert<'documents'>
export type WorkflowInsert = TablesInsert<'workflows'>
export type ApprovalInsert = TablesInsert<'approvals'>
export type AuditLogInsert = TablesInsert<'audit_logs'>
export type NotificationInsert = TablesInsert<'notifications'>

// Update types
export type UserUpdate = TablesUpdate<'users'>
export type DocumentUpdate = TablesUpdate<'documents'>
export type WorkflowUpdate = TablesUpdate<'workflows'>
export type ApprovalUpdate = TablesUpdate<'approvals'>
export type AuditLogUpdate = TablesUpdate<'audit_logs'>
export type NotificationUpdate = TablesUpdate<'notifications'>
